# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 05c74928b49034b1ccc60cb0520898a2e35a2e898c2a6d7c800bb2f5cf177c3eeca9b6c6baa0c30ab54fcedded585c0b5162981043e425c7836053ab7bc71c31

test:
  secret_key_base: 28b7b42c6bee1f7318de7dc4f78c75f2abd93d2f15020694f8401d8922574fabb716ad47ea00a48707bc76537c88a0415705a7c7fde09694ac5cffec6ddd8b80

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
